name: flutter_pokeapi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  go_router: ^13.2.2
  json_annotation: ^4.8.1
  local_auth: ^2.2.0
  logger: any  #for logging purpose
  retrofit: '>=4.0.0 <5.0.0'
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: 
  custom_lint:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.2
  retrofit_generator: '>=7.0.0 <8.0.0'
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
